/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponse,
  ExportUserDataResponse,
  GetAuthenticatedUserResponse,
  UpdateAuthenticatedUserBody,
  UpdateAuthenticatedUserResponse
} from '../schemas';





export type getApiV1UsersMeResponse200 = {
  data: GetAuthenticatedUserResponse
  status: 200
}

export type getApiV1UsersMeResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getApiV1UsersMeResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1UsersMeResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1UsersMeResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1UsersMeResponseSuccess = (getApiV1UsersMeResponse200) & {
  headers: Headers;
};
export type getApiV1UsersMeResponseError = (getApiV1UsersMeResponse401 | getApiV1UsersMeResponse404 | getApiV1UsersMeResponse429 | getApiV1UsersMeResponse500) & {
  headers: Headers;
};

export type getApiV1UsersMeResponse = (getApiV1UsersMeResponseSuccess | getApiV1UsersMeResponseError)

export const getGetApiV1UsersMeUrl = () => {




  return `/api/v1/users/@me`
}

/**
 * Retorna os dados do usuário autenticado.
 * @summary Obter usuário autenticado
 */
export const getApiV1UsersMe = async ( options?: RequestInit): Promise<getApiV1UsersMeResponse> => {

  const res = await fetch(getGetApiV1UsersMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1UsersMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1UsersMeResponse
}





export const getGetApiV1UsersMeQueryKey = () => {
    return [
    `/api/v1/users/@me`
    ] as const;
    }


export const getGetApiV1UsersMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = ApiErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UsersMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersMe>>> = ({ signal }) => getApiV1UsersMe({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1UsersMe>>>
export type GetApiV1UsersMeQueryError = ApiErrorResponse


export function useGetApiV1UsersMe<TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = ApiErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersMe<TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersMe<TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter usuário autenticado
 */

export function useGetApiV1UsersMe<TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1UsersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchApiV1UsersMeResponse200 = {
  data: UpdateAuthenticatedUserResponse
  status: 200
}

export type patchApiV1UsersMeResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type patchApiV1UsersMeResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type patchApiV1UsersMeResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type patchApiV1UsersMeResponse409 = {
  data: ApiErrorResponse
  status: 409
}

export type patchApiV1UsersMeResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type patchApiV1UsersMeResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type patchApiV1UsersMeResponseSuccess = (patchApiV1UsersMeResponse200) & {
  headers: Headers;
};
export type patchApiV1UsersMeResponseError = (patchApiV1UsersMeResponse400 | patchApiV1UsersMeResponse401 | patchApiV1UsersMeResponse404 | patchApiV1UsersMeResponse409 | patchApiV1UsersMeResponse429 | patchApiV1UsersMeResponse500) & {
  headers: Headers;
};

export type patchApiV1UsersMeResponse = (patchApiV1UsersMeResponseSuccess | patchApiV1UsersMeResponseError)

export const getPatchApiV1UsersMeUrl = () => {




  return `/api/v1/users/@me`
}

/**
 * Atualiza os dados do usuário autenticado.
 * @summary Atualizar usuário autenticado
 */
export const patchApiV1UsersMe = async (updateAuthenticatedUserBody?: UpdateAuthenticatedUserBody, options?: RequestInit): Promise<patchApiV1UsersMeResponse> => {

  const res = await fetch(getPatchApiV1UsersMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAuthenticatedUserBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchApiV1UsersMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiV1UsersMeResponse
}




export const getPatchApiV1UsersMeMutationOptions = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UsersMe>>, TError,{data?: UpdateAuthenticatedUserBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UsersMe>>, TError,{data?: UpdateAuthenticatedUserBody}, TContext> => {

const mutationKey = ['patchApiV1UsersMe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1UsersMe>>, {data?: UpdateAuthenticatedUserBody}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1UsersMe(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1UsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1UsersMe>>>
    export type PatchApiV1UsersMeMutationBody = UpdateAuthenticatedUserBody | undefined
    export type PatchApiV1UsersMeMutationError = ApiErrorResponse

    /**
 * @summary Atualizar usuário autenticado
 */
export const usePatchApiV1UsersMe = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1UsersMe>>, TError,{data?: UpdateAuthenticatedUserBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1UsersMe>>,
        TError,
        {data?: UpdateAuthenticatedUserBody},
        TContext
      > => {
      return useMutation(getPatchApiV1UsersMeMutationOptions(options), queryClient);
    }
    export type deleteApiV1UsersMeResponse204 = {
  data: void
  status: 204
}

export type deleteApiV1UsersMeResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type deleteApiV1UsersMeResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type deleteApiV1UsersMeResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type deleteApiV1UsersMeResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type deleteApiV1UsersMeResponseSuccess = (deleteApiV1UsersMeResponse204) & {
  headers: Headers;
};
export type deleteApiV1UsersMeResponseError = (deleteApiV1UsersMeResponse401 | deleteApiV1UsersMeResponse404 | deleteApiV1UsersMeResponse429 | deleteApiV1UsersMeResponse500) & {
  headers: Headers;
};

export type deleteApiV1UsersMeResponse = (deleteApiV1UsersMeResponseSuccess | deleteApiV1UsersMeResponseError)

export const getDeleteApiV1UsersMeUrl = () => {




  return `/api/v1/users/@me`
}

/**
 * Remove a conta do usuário e todos os dados associados (direito de eliminação LGPD Art. 18, VI).
 * @summary Deletar usuário autenticado
 */
export const deleteApiV1UsersMe = async ( options?: RequestInit): Promise<deleteApiV1UsersMeResponse> => {

  const res = await fetch(getDeleteApiV1UsersMeUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiV1UsersMeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiV1UsersMeResponse
}




export const getDeleteApiV1UsersMeMutationOptions = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersMe>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersMe>>, TError,void, TContext> => {

const mutationKey = ['deleteApiV1UsersMe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1UsersMe>>, void> = () => {


          return  deleteApiV1UsersMe(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1UsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1UsersMe>>>

    export type DeleteApiV1UsersMeMutationError = ApiErrorResponse

    /**
 * @summary Deletar usuário autenticado
 */
export const useDeleteApiV1UsersMe = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersMe>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1UsersMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteApiV1UsersMeMutationOptions(options), queryClient);
    }
    export type getApiV1UsersMeExportResponse200 = {
  data: ExportUserDataResponse
  status: 200
}

export type getApiV1UsersMeExportResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getApiV1UsersMeExportResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1UsersMeExportResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1UsersMeExportResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1UsersMeExportResponseSuccess = (getApiV1UsersMeExportResponse200) & {
  headers: Headers;
};
export type getApiV1UsersMeExportResponseError = (getApiV1UsersMeExportResponse401 | getApiV1UsersMeExportResponse404 | getApiV1UsersMeExportResponse429 | getApiV1UsersMeExportResponse500) & {
  headers: Headers;
};

export type getApiV1UsersMeExportResponse = (getApiV1UsersMeExportResponseSuccess | getApiV1UsersMeExportResponseError)

export const getGetApiV1UsersMeExportUrl = () => {




  return `/api/v1/users/@me/export`
}

/**
 * Exporta todos os dados pessoais do usuário (direito de portabilidade LGPD Art. 18, II e V).
 * @summary Exportar dados do usuário autenticado
 */
export const getApiV1UsersMeExport = async ( options?: RequestInit): Promise<getApiV1UsersMeExportResponse> => {

  const res = await fetch(getGetApiV1UsersMeExportUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1UsersMeExportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1UsersMeExportResponse
}





export const getGetApiV1UsersMeExportQueryKey = () => {
    return [
    `/api/v1/users/@me/export`
    ] as const;
    }


export const getGetApiV1UsersMeExportQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError = ApiErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UsersMeExportQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersMeExport>>> = ({ signal }) => getApiV1UsersMeExport({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1UsersMeExportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1UsersMeExport>>>
export type GetApiV1UsersMeExportQueryError = ApiErrorResponse


export function useGetApiV1UsersMeExport<TData = Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError = ApiErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersMeExport>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersMeExport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersMeExport<TData = Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersMeExport>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersMeExport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1UsersMeExport<TData = Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Exportar dados do usuário autenticado
 */

export function useGetApiV1UsersMeExport<TData = Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMeExport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1UsersMeExportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






