/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type {
  GetApiV1ReadingsJourneyFeedParams,
  JourneyFeedResponse,
  JourneyNextProgressResponse,
  JourneyStatusResponse
} from '../schemas';

import getApiV1ReadingsJourneyFeedMutator from '../../../../lib/api-fetcher';
import postApiV1ReadingsJourneyNextMutator from '../../../../lib/api-fetcher';
import getApiV1ReadingsJourneyStatusMutator from '../../../../lib/api-fetcher';

export const getGetApiV1ReadingsJourneyFeedUrl = (params?: GetApiV1ReadingsJourneyFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/readings/journey/feed?${stringifiedParams}` : `/api/v1/readings/journey/feed`
}

/**
 * Retorna o capítulo atual e os próximos itens para pre-fetch.
 * @summary Feed de leitura
 */
export const getApiV1ReadingsJourneyFeed = async (params?: GetApiV1ReadingsJourneyFeedParams, options?: RequestInit): Promise<JourneyFeedResponse> => {

  return getApiV1ReadingsJourneyFeedMutator<JourneyFeedResponse>(getGetApiV1ReadingsJourneyFeedUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPostApiV1ReadingsJourneyNextUrl = () => {




  return `/api/v1/readings/journey/next`
}

/**
 * Salva o capítulo atual como lido e avança para o próximo.
 * @summary Avançar progresso
 */
export const postApiV1ReadingsJourneyNext = async ( options?: RequestInit): Promise<JourneyNextProgressResponse> => {

  return postApiV1ReadingsJourneyNextMutator<JourneyNextProgressResponse>(getPostApiV1ReadingsJourneyNextUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export const getGetApiV1ReadingsJourneyStatusUrl = () => {




  return `/api/v1/readings/journey/status`
}

/**
 * Retorna o status atual do progresso de leitura.
 * @summary Status da jornada
 */
export const getApiV1ReadingsJourneyStatus = async ( options?: RequestInit): Promise<JourneyStatusResponse> => {

  return getApiV1ReadingsJourneyStatusMutator<JourneyStatusResponse>(getGetApiV1ReadingsJourneyStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


