/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import * as zod from 'zod';


/**
 * Retorna todos os versículos de um capítulo para leitura no modo Discovery.
 * @summary Versículos do capítulo
 */
export const GetApiV1ReadingsDiscoveryNextQueryParams = zod.object({
  "chapterId": zod.uuid().optional().describe('ID do capítulo (opcional)')
})

export const getApiV1ReadingsDiscoveryNextResponseSuccessDefault = true;
export const getApiV1ReadingsDiscoveryNextResponseDataItemNumberExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryNextResponseDataItemChapterNumberExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryNextResponseDataItemBookOrderExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryNextResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryNextResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryNextResponsePaginationTotalItemsMin = 0;

export const getApiV1ReadingsDiscoveryNextResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1ReadingsDiscoveryNextResponse = zod.object({
  "success": zod.boolean().default(getApiV1ReadingsDiscoveryNextResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.array(zod.object({
  "id": zod.uuid().describe('ID do versículo'),
  "number": zod.number().gt(getApiV1ReadingsDiscoveryNextResponseDataItemNumberExclusiveMin).describe('Número do versículo'),
  "text": zod.string().describe('Texto do versículo'),
  "chapter": zod.object({
  "id": zod.uuid().describe('ID do capítulo'),
  "number": zod.number().gt(getApiV1ReadingsDiscoveryNextResponseDataItemChapterNumberExclusiveMin).describe('Número do capítulo')
}),
  "book": zod.object({
  "id": zod.uuid().describe('ID do livro'),
  "order": zod.number().gt(getApiV1ReadingsDiscoveryNextResponseDataItemBookOrderExclusiveMin).describe('Ordem canônica do livro (1-73)'),
  "name": zod.string().describe('Nome do livro'),
  "slug": zod.string().describe('Slug do livro')
})
})).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1ReadingsDiscoveryNextResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1ReadingsDiscoveryNextResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1ReadingsDiscoveryNextResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1ReadingsDiscoveryNextResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para DiscoveryNextVersesResponse')

/**
 * Registra que o usuário leu versículos específicos.
 * @summary Marcar versículos como lidos
 */
export const PostApiV1ReadingsDiscoveryBody = zod.object({
  "verseIds": zod.array(zod.uuid()).describe('IDs dos versículos lidos')
})

export const postApiV1ReadingsDiscoveryResponseSuccessDefault = true;
export const postApiV1ReadingsDiscoveryResponsePaginationCurrentPageExclusiveMin = 0;

export const postApiV1ReadingsDiscoveryResponsePaginationTotalPagesExclusiveMin = 0;

export const postApiV1ReadingsDiscoveryResponsePaginationTotalItemsMin = 0;

export const postApiV1ReadingsDiscoveryResponsePaginationItemsPerPageExclusiveMin = 0;



export const PostApiV1ReadingsDiscoveryResponse = zod.object({
  "success": zod.boolean().default(postApiV1ReadingsDiscoveryResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.object({
  "success": zod.boolean()
}).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(postApiV1ReadingsDiscoveryResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(postApiV1ReadingsDiscoveryResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(postApiV1ReadingsDiscoveryResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(postApiV1ReadingsDiscoveryResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para DiscoveryMarkVersesResponse')

/**
 * Retorna estatísticas de leitura no modo Discovery.
 * @summary Estatísticas do Discovery
 */
export const getApiV1ReadingsDiscoveryStatsResponseSuccessDefault = true;
export const getApiV1ReadingsDiscoveryStatsResponseDataVersesReadMin = 0;

export const getApiV1ReadingsDiscoveryStatsResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryStatsResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1ReadingsDiscoveryStatsResponsePaginationTotalItemsMin = 0;

export const getApiV1ReadingsDiscoveryStatsResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1ReadingsDiscoveryStatsResponse = zod.object({
  "success": zod.boolean().default(getApiV1ReadingsDiscoveryStatsResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.object({
  "versesRead": zod.number().min(getApiV1ReadingsDiscoveryStatsResponseDataVersesReadMin).describe('Total de versículos lidos')
}).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1ReadingsDiscoveryStatsResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1ReadingsDiscoveryStatsResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1ReadingsDiscoveryStatsResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1ReadingsDiscoveryStatsResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para DiscoveryStatsResponse')

