services:
  postgres:
    image: postgres:16-alpine
    container_name: versum-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: versum-redis
    restart: unless-stopped
    network_mode: host
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
