/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type {
  AuthenticateWithMagicLinkResponse,
  GetApiV1AuthMagicLinkParams,
  LogoutResponse,
  SendMagicLinkBody,
  SendMagicLinkResponse
} from '../schemas';

import postApiV1AuthMagicLinkMutator from '../../../../lib/api-fetcher';
import getApiV1AuthMagicLinkMutator from '../../../../lib/api-fetcher';
import postApiV1AuthLogoutMutator from '../../../../lib/api-fetcher';

export const getPostApiV1AuthMagicLinkUrl = () => {




  return `/api/v1/auth/magic-link`
}

/**
 * Envia um link mágico para autenticação via e-mail.
 * @summary Enviar magic link
 */
export const postApiV1AuthMagicLink = async (sendMagicLinkBody?: SendMagicLinkBody, options?: RequestInit): Promise<SendMagicLinkResponse> => {

  return postApiV1AuthMagicLinkMutator<SendMagicLinkResponse>(getPostApiV1AuthMagicLinkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sendMagicLinkBody)
  }
);}


export const getGetApiV1AuthMagicLinkUrl = (params: GetApiV1AuthMagicLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/magic-link?${stringifiedParams}` : `/api/v1/auth/magic-link`
}

/**
 * Cria uma sessão a partir de um token de magic link.
 * @summary Autenticar com magic link
 */
export const getApiV1AuthMagicLink = async (params: GetApiV1AuthMagicLinkParams, options?: RequestInit): Promise<AuthenticateWithMagicLinkResponse> => {

  return getApiV1AuthMagicLinkMutator<AuthenticateWithMagicLinkResponse>(getGetApiV1AuthMagicLinkUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export const getPostApiV1AuthLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * Encerra a sessão atual baseada no cookie de sessão.
 * @summary Encerrar sessão
 */
export const postApiV1AuthLogout = async ( options?: RequestInit): Promise<LogoutResponse> => {

  return postApiV1AuthLogoutMutator<LogoutResponse>(getPostApiV1AuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


