/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import * as zod from 'zod';


/**
 * Retorna os dados do usuário autenticado.
 * @summary Obter usuário autenticado
 */
export const getApiV1UsersMeResponseUserEmailMax = 255;



export const GetApiV1UsersMeResponse = zod.object({
  "user": zod.object({
  "email": zod.email().max(getApiV1UsersMeResponseUserEmailMax).describe('E-mail do usuário')
}).describe('Dados privados do usuário'),
  "onboardingIsCompleted": zod.boolean()
}).describe('Usuário autenticado retornado com sucesso')

/**
 * Atualiza os dados do usuário autenticado.
 * @summary Atualizar usuário autenticado
 */
export const patchApiV1UsersMeBodyEmailMax = 255;



export const PatchApiV1UsersMeBody = zod.object({
  "email": zod.email().max(patchApiV1UsersMeBodyEmailMax).describe('E-mail do usuário')
}).describe('Payload para atualizar os dados do usuário autenticado')

export const patchApiV1UsersMeResponseUserEmailMax = 255;



export const PatchApiV1UsersMeResponse = zod.object({
  "user": zod.object({
  "email": zod.email().max(patchApiV1UsersMeResponseUserEmailMax).describe('E-mail do usuário')
}).describe('Dados privados do usuário')
}).describe('Usuário autenticado atualizado com sucesso')

/**
 * Exporta todos os dados pessoais do usuário (direito de portabilidade LGPD Art. 18, II e V).
 * @summary Exportar dados do usuário autenticado
 */
export const GetApiV1UsersMeExportResponse = zod.object({
  "exportedAt": zod.iso.datetime({"offset":true}).describe('Data e hora da exportação'),
  "user": zod.object({
  "email": zod.email(),
  "createdAt": zod.iso.datetime({"offset":true})
}).describe('Dados do usuário'),
  "profile": zod.object({
  "username": zod.string(),
  "name": zod.string(),
  "bio": zod.string().nullable(),
  "pictureUrl": zod.string().nullable()
}).nullable().describe('Perfil do usuário'),
  "sessions": zod.array(zod.object({
  "createdAt": zod.iso.datetime({"offset":true}),
  "ip": zod.string(),
  "userAgent": zod.string(),
  "expiresAt": zod.iso.datetime({"offset":true})
})).describe('Sessões do usuário'),
  "readingHistory": zod.object({
  "journey": zod.array(zod.object({
  "chapterId": zod.string(),
  "readAt": zod.iso.datetime({"offset":true})
})),
  "discovery": zod.array(zod.object({
  "verseId": zod.string(),
  "readAt": zod.iso.datetime({"offset":true})
}))
}).describe('Histórico de leitura'),
  "annotations": zod.array(zod.object({
  "verseId": zod.string(),
  "selectedVerseId": zod.string(),
  "annotation": zod.string().nullable(),
  "isPublic": zod.boolean(),
  "createdAt": zod.iso.datetime({"offset":true})
})).describe('Anotações do usuário'),
  "likes": zod.array(zod.object({
  "verseId": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true})
})).describe('Favoritos do usuário'),
  "consentLogs": zod.array(zod.object({
  "id": zod.string().describe('ID do registro de consentimento'),
  "userId": zod.string().describe('ID do usuário'),
  "purpose": zod.string().describe('Finalidade do consentimento'),
  "granted": zod.boolean().describe('Se o consentimento foi concedido'),
  "ip": zod.string().describe('Endereço IP'),
  "userAgent": zod.string().describe('User-Agent'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('Data do registro')
}).describe('Registro de consentimento')).describe('Histórico de consentimento')
}).describe('Dados do usuário exportados com sucesso (LGPD Art. 18, II e V)')

