/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { CheckUsernameAvailabilityResponseData } from './checkUsernameAvailabilityResponseData';

/**
 * Resposta de sucesso para CheckUsernameAvailabilityResponse
 */
export interface CheckUsernameAvailabilityResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem de contexto da resposta */
  message: string;
  /** Código da resposta */
  code: string;
  /** Dados da resposta */
  data?: CheckUsernameAvailabilityResponseData;
}
