/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ConsentLog } from './consentLog';

/**
 * Histórico de consentimentos do usuário
 */
export interface ConsentHistoryResponse {
  consents: ConsentLog[];
}
