/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Finalidade do consentimento
 */
export type ConsentItemPurpose = typeof ConsentItemPurpose[keyof typeof ConsentItemPurpose];


export const ConsentItemPurpose = {
  profile_content: 'profile_content',
  annotations: 'annotations',
  likes: 'likes',
  terms: 'terms',
} as const;
