/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ConsentItemPurpose } from './consentItemPurpose';

/**
 * Item de consentimento
 */
export interface ConsentItem {
  /** Finalidade do consentimento */
  purpose: ConsentItemPurpose;
  /** true = concedido, false = revogado */
  granted: boolean;
}
