/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type DiscoveryNextVersesResponseDataItemChapter = {
  /** ID do capítulo */
  id: string;
  /**
     * Número do capítulo
     * @exclusiveMinimum 0
     */
  number: number;
};
