/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Dados da resposta
 */
export type DiscoveryStatsResponseData = {
  /**
     * Total de versículos lidos
     * @minimum 0
     */
  versesRead: number;
};
