/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Perfil do usuário
 * @nullable
 */
export type ExportProfile = {
  username: string;
  name: string;
  /** @nullable */
  bio: string | null;
  /** @nullable */
  pictureUrl: string | null;
} | null;
