/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ExportUserData } from './exportUserData';

/**
 * Resposta de sucesso para ExportUserDataResponse
 */
export interface ExportUserDataResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  data?: ExportUserData;
}
