/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type ExportUserDataAnnotationsItem = {
  verseId: string;
  selectedVerseId: string;
  /** @nullable */
  annotation: string | null;
  isPublic: boolean;
  createdAt: string;
};
