/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Dados do usuário
 */
export interface ExportUser {
  email: string;
  createdAt: string;
}
