/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { Chapter } from './chapter';
import type { PaginationViewModel } from './paginationViewModel';

/**
 * Resposta de sucesso para GetChapterResponse
 */
export interface GetChapterResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  data?: Chapter & unknown;
  pagination?: PaginationViewModel;
}
