/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { JourneyStatusResponseData } from './journeyStatusResponseData';

/**
 * Resposta de sucesso para JourneyStatusResponse
 */
export interface JourneyStatusResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem de contexto da resposta */
  message: string;
  /** Código da resposta */
  code: string;
  /** Dados da resposta */
  data?: JourneyStatusResponseData;
}
