/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Próximo capítulo a ler
 * @nullable
 */
export type JourneyFeedResponseDataCurrent = {
  chapter: {
  /** ID do capítulo */
  id: string;
  /**
     * Número do capítulo
     * @exclusiveMinimum 0
     */
  number: number;
  /**
     * Total de versículos
     * @exclusiveMinimum 0
     */
  totalVerses: number;
};
  book: {
  /** ID do livro */
  id: string;
  /**
     * Ordem canônica do livro (1-73)
     * @exclusiveMinimum 0
     */
  order: number;
  /** Nome do livro */
  name: string;
  /** Slug do livro */
  slug: string;
};
  verses: {
  /** ID do versículo */
  id: string;
  /**
     * Número do versículo
     * @exclusiveMinimum 0
     */
  number: number;
  /** Texto do versículo */
  text: string;
}[];
} | null;
