/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { JourneyFeedResponseDataNextItemsItemBook } from './journeyFeedResponseDataNextItemsItemBook';
import type { JourneyFeedResponseDataNextItemsItemChapter } from './journeyFeedResponseDataNextItemsItemChapter';
import type { JourneyFeedResponseDataNextItemsItemVersesItem } from './journeyFeedResponseDataNextItemsItemVersesItem';

export type JourneyFeedResponseDataNextItemsItem = {
  chapter: JourneyFeedResponseDataNextItemsItemChapter;
  book: JourneyFeedResponseDataNextItemsItemBook;
  verses: JourneyFeedResponseDataNextItemsItemVersesItem[];
};
