/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Sessão encerrada com sucesso
 */
export interface LogoutResponse {
  /** Mensagem legível para humanos */
  message: string;
}
