/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type PostApiV1ReadingsJourneyNextBody = {
  /** ID do capítulo que o cliente está confirmando como lido */
  chapterId: string;
};
