/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ConsentItem } from './consentItem';

/**
 * Payload para registrar consentimentos
 */
export interface RecordConsentBody {
  /**
     * Lista de consentimentos
     * @minItems 1
     */
  consents: ConsentItem[];
}
