/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { FullProfile } from './fullProfile';

/**
 * Resposta de sucesso para UpdateAuthenticatedProfileResponse
 */
export interface UpdateAuthenticatedProfileResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  data?: FullProfile;
}
