/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Payload para atualizar o perfil do usuário autenticado
 */
export interface UpdateAuthenticatedProfileBody {
  /**
     * Username único
     * @minLength 3
     * @maxLength 50
     * @pattern ^[a-zA-Z0-9_]+$
     */
  username?: string;
  /**
     * Nome de exibição
     * @minLength 1
     * @maxLength 100
     */
  name?: string;
  /**
     * Biografia do usuário
     * @maxLength 500
     * @nullable
     */
  bio?: string | null;
  /**
     * URL da foto de perfil
     * @maxLength 500
     * @nullable
     */
  pictureUrl?: string | null;
}
