/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Payload para atualizar os dados do usuário autenticado
 */
export interface UpdateAuthenticatedUserBody {
  /**
     * E-mail do usuário
     * @maxLength 255
     */
  email: string;
}
