/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Multipart form data with profile picture file
 */
export interface UploadProfilePictureBody {
  /** Profile picture file (JPEG or PNG, max 5MB) */
  file?: Blob;
}
