/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Dados privados do usuário
 */
export interface User {
  /**
     * E-mail do usuário
     * @maxLength 255
     */
  email: string;
}
