/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponse,
  AuthenticateWithMagicLinkResponse,
  GetApiV1AuthMagicLinkParams,
  LogoutResponse,
  SendMagicLinkBody,
  SendMagicLinkResponse
} from '../schemas';





export type postApiV1AuthMagicLinkResponse200 = {
  data: SendMagicLinkResponse
  status: 200
}

export type postApiV1AuthMagicLinkResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type postApiV1AuthMagicLinkResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type postApiV1AuthMagicLinkResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type postApiV1AuthMagicLinkResponseSuccess = (postApiV1AuthMagicLinkResponse200) & {
  headers: Headers;
};
export type postApiV1AuthMagicLinkResponseError = (postApiV1AuthMagicLinkResponse400 | postApiV1AuthMagicLinkResponse429 | postApiV1AuthMagicLinkResponse500) & {
  headers: Headers;
};

export type postApiV1AuthMagicLinkResponse = (postApiV1AuthMagicLinkResponseSuccess | postApiV1AuthMagicLinkResponseError)

export const getPostApiV1AuthMagicLinkUrl = () => {




  return `/api/v1/auth/magic-link`
}

/**
 * Envia um link mágico para autenticação via e-mail.
 * @summary Enviar magic link
 */
export const postApiV1AuthMagicLink = async (sendMagicLinkBody?: SendMagicLinkBody, options?: RequestInit): Promise<postApiV1AuthMagicLinkResponse> => {

  const res = await fetch(getPostApiV1AuthMagicLinkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sendMagicLinkBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1AuthMagicLinkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1AuthMagicLinkResponse
}




export const getPostApiV1AuthMagicLinkMutationOptions = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthMagicLink>>, TError,{data?: SendMagicLinkBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthMagicLink>>, TError,{data?: SendMagicLinkBody}, TContext> => {

const mutationKey = ['postApiV1AuthMagicLink'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthMagicLink>>, {data?: SendMagicLinkBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthMagicLink(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthMagicLinkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthMagicLink>>>
    export type PostApiV1AuthMagicLinkMutationBody = SendMagicLinkBody | undefined
    export type PostApiV1AuthMagicLinkMutationError = ApiErrorResponse

    /**
 * @summary Enviar magic link
 */
export const usePostApiV1AuthMagicLink = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthMagicLink>>, TError,{data?: SendMagicLinkBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthMagicLink>>,
        TError,
        {data?: SendMagicLinkBody},
        TContext
      > => {
      return useMutation(getPostApiV1AuthMagicLinkMutationOptions(options), queryClient);
    }
    export type getApiV1AuthMagicLinkResponse200 = {
  data: AuthenticateWithMagicLinkResponse
  status: 200
}

export type getApiV1AuthMagicLinkResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1AuthMagicLinkResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getApiV1AuthMagicLinkResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1AuthMagicLinkResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1AuthMagicLinkResponseSuccess = (getApiV1AuthMagicLinkResponse200) & {
  headers: Headers;
};
export type getApiV1AuthMagicLinkResponseError = (getApiV1AuthMagicLinkResponse400 | getApiV1AuthMagicLinkResponse401 | getApiV1AuthMagicLinkResponse429 | getApiV1AuthMagicLinkResponse500) & {
  headers: Headers;
};

export type getApiV1AuthMagicLinkResponse = (getApiV1AuthMagicLinkResponseSuccess | getApiV1AuthMagicLinkResponseError)

export const getGetApiV1AuthMagicLinkUrl = (params: GetApiV1AuthMagicLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/magic-link?${stringifiedParams}` : `/api/v1/auth/magic-link`
}

/**
 * Cria uma sessão a partir de um token de magic link.
 * @summary Autenticar com magic link
 */
export const getApiV1AuthMagicLink = async (params: GetApiV1AuthMagicLinkParams, options?: RequestInit): Promise<getApiV1AuthMagicLinkResponse> => {

  const res = await fetch(getGetApiV1AuthMagicLinkUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1AuthMagicLinkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1AuthMagicLinkResponse
}





export const getGetApiV1AuthMagicLinkQueryKey = (params?: GetApiV1AuthMagicLinkParams,) => {
    return [
    `/api/v1/auth/magic-link`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1AuthMagicLinkQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError = ApiErrorResponse>(params: GetApiV1AuthMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthMagicLinkQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>> = ({ signal }) => getApiV1AuthMagicLink(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthMagicLinkQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>>
export type GetApiV1AuthMagicLinkQueryError = ApiErrorResponse


export function useGetApiV1AuthMagicLink<TData = Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError = ApiErrorResponse>(
 params: GetApiV1AuthMagicLinkParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthMagicLink>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthMagicLink>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthMagicLink<TData = Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError = ApiErrorResponse>(
 params: GetApiV1AuthMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthMagicLink>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthMagicLink>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthMagicLink<TData = Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError = ApiErrorResponse>(
 params: GetApiV1AuthMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Autenticar com magic link
 */

export function useGetApiV1AuthMagicLink<TData = Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError = ApiErrorResponse>(
 params: GetApiV1AuthMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthMagicLink>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthMagicLinkQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postApiV1AuthLogoutResponse200 = {
  data: LogoutResponse
  status: 200
}

export type postApiV1AuthLogoutResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type postApiV1AuthLogoutResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type postApiV1AuthLogoutResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type postApiV1AuthLogoutResponseSuccess = (postApiV1AuthLogoutResponse200) & {
  headers: Headers;
};
export type postApiV1AuthLogoutResponseError = (postApiV1AuthLogoutResponse400 | postApiV1AuthLogoutResponse429 | postApiV1AuthLogoutResponse500) & {
  headers: Headers;
};

export type postApiV1AuthLogoutResponse = (postApiV1AuthLogoutResponseSuccess | postApiV1AuthLogoutResponseError)

export const getPostApiV1AuthLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * Encerra a sessão atual baseada no cookie de sessão.
 * @summary Encerrar sessão
 */
export const postApiV1AuthLogout = async ( options?: RequestInit): Promise<postApiV1AuthLogoutResponse> => {

  const res = await fetch(getPostApiV1AuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1AuthLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1AuthLogoutResponse
}




export const getPostApiV1AuthLogoutMutationOptions = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postApiV1AuthLogout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogout>>, void> = () => {


          return  postApiV1AuthLogout(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogout>>>

    export type PostApiV1AuthLogoutMutationError = ApiErrorResponse

    /**
 * @summary Encerrar sessão
 */
export const usePostApiV1AuthLogout = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1AuthLogoutMutationOptions(options), queryClient);
    }
