/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Capítulo de um livro da Bíblia
 */
export interface Chapter {
  /** ID único do capítulo */
  id: string;
  /** ID do livro ao qual o capítulo pertence */
  bookId: string;
  /**
     * Número do capítulo
     * @exclusiveMinimum 0
     */
  number: number;
  /**
     * Número total de versículos
     * @exclusiveMinimum 0
     */
  totalVerses: number;
}
