/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { Profile } from './profile';

/**
 * Perfil criado com sucesso
 */
export interface CreateProfileResponse {
  profile: Profile;
}
