/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { DiscoveryNextVersesResponseDataItemBook } from './discoveryNextVersesResponseDataItemBook';
import type { DiscoveryNextVersesResponseDataItemChapter } from './discoveryNextVersesResponseDataItemChapter';

export type DiscoveryNextVersesResponseDataItem = {
  /** ID do versículo */
  id: string;
  /**
     * Número do versículo
     * @exclusiveMinimum 0
     */
  number: number;
  /** Texto do versículo */
  text: string;
  chapter: DiscoveryNextVersesResponseDataItemChapter;
  book: DiscoveryNextVersesResponseDataItemBook;
};
