/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { DiscoveryStatsResponseData } from './discoveryStatsResponseData';
import type { PaginationViewModel } from './paginationViewModel';

/**
 * Resposta de sucesso para DiscoveryStatsResponse
 */
export interface DiscoveryStatsResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  /** Dados da resposta */
  data?: DiscoveryStatsResponseData;
  pagination?: PaginationViewModel;
}
