/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ExportConsentLog } from './exportConsentLog';
import type { ExportProfile } from './exportProfile';
import type { ExportReadingHistory } from './exportReadingHistory';
import type { ExportUser } from './exportUser';
import type { ExportUserDataAnnotationsItem } from './exportUserDataAnnotationsItem';
import type { ExportUserDataLikesItem } from './exportUserDataLikesItem';
import type { ExportUserDataSessionsItem } from './exportUserDataSessionsItem';

/**
 * Dados da resposta
 */
export interface ExportUserData {
  /** Data e hora da exportação */
  exportedAt: string;
  user: ExportUser;
  profile: ExportProfile | null;
  /** Sessões do usuário */
  sessions: ExportUserDataSessionsItem[];
  readingHistory: ExportReadingHistory;
  /** Anotações do usuário */
  annotations: ExportUserDataAnnotationsItem[];
  /** Favoritos do usuário */
  likes: ExportUserDataLikesItem[];
  /** Histórico de consentimento */
  consentLogs: ExportConsentLog[];
}
