/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type ExportReadingHistoryJourneyItem = {
  chapterId: string;
  readAt: string;
};
