/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type GetApiV1ReadingsJourneyFeedParams = {
/**
 * Quantidade de itens no pre-fetch (0-4, padrão: 4)
 * @minimum 0
 * @maximum 4
 * @nullable
 */
'buffer-size'?: number | null;
};
