/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { Book } from './book';
import type { PaginationViewModel } from './paginationViewModel';

/**
 * Resposta de sucesso para GetBookByDynamicIdResponse
 */
export interface GetBookByDynamicIdResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  data?: Book & unknown;
  pagination?: PaginationViewModel;
}
