/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Informações de paginação
 */
export interface PaginationViewModel {
  /**
     * Página atual
     * @exclusiveMinimum 0
     */
  currentPage: number;
  /**
     * Número total de páginas
     * @exclusiveMinimum 0
     */
  totalPages: number;
  /**
     * Número total de itens
     * @minimum 0
     */
  totalItems: number;
  /**
     * Número de itens por página
     * @exclusiveMinimum 0
     */
  itemsPerPage: number;
  /** Indica se existe próxima página */
  hasNextPage: boolean;
  /** Indica se existe página anterior */
  hasPrevPage: boolean;
}
