/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Solicitação de magic link aceita
 */
export interface SendMagicLinkResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem legível para humanos */
  message?: string;
}
