/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Versículo de um capítulo da Bíblia
 */
export interface Verse {
  /** ID único do versículo */
  id: string;
  /** ID do capítulo ao qual o versículo pertence */
  chapterId: string;
  /**
     * Número do versículo
     * @exclusiveMinimum 0
     */
  number: number;
  /** Texto do versículo */
  text: string;
}
