/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Resposta padrão de erro da API
 */
export interface ApiErrorResponse {
  /** Indica que ocorreu um erro */
  success: false;
  /** Mensagem de erro */
  error: string;
  /** Código do erro */
  code?: string;
}
