/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Testamento ao qual o livro pertence
 */
export type BookTestament = typeof BookTestament[keyof typeof BookTestament];


export const BookTestament = {
  OLD: 'OLD',
  NEW: 'NEW',
} as const;
