/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Registro de consentimento
 */
export interface ConsentLog {
  id: string;
  userId: string;
  purpose: string;
  granted: boolean;
  ip: string;
  userAgent: string;
  createdAt: string;
}
