/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Registro de consentimento
 */
export interface ExportConsentLog {
  /** ID do registro de consentimento */
  id: string;
  /** ID do usuário */
  userId: string;
  /** Finalidade do consentimento */
  purpose: string;
  /** Se o consentimento foi concedido */
  granted: boolean;
  /** Endereço IP */
  ip: string;
  /** User-Agent */
  userAgent: string;
  /** Data do registro */
  createdAt: string;
}
