/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { ExportReadingHistoryDiscoveryItem } from './exportReadingHistoryDiscoveryItem';
import type { ExportReadingHistoryJourneyItem } from './exportReadingHistoryJourneyItem';

/**
 * Histórico de leitura
 */
export interface ExportReadingHistory {
  journey: ExportReadingHistoryJourneyItem[];
  discovery: ExportReadingHistoryDiscoveryItem[];
}
