/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type GetApiV1PublicBibleBooksParams = {
/**
 * Número da página (padrão: 1)
 * @minimum 1
 */
page?: number;
/**
 * Limite de itens por página (padrão: 10)
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
