/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type GetApiV1AuthMagicLinkParams = {
/**
 * Token do magic link (public_id.token)
 * @minLength 1
 */
token: string;
};
