/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { Verse } from './verse';

/**
 * Resposta de sucesso para GetVerseResponse
 */
export interface GetVerseResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem de contexto da resposta */
  message: string;
  /** Código da resposta */
  code: string;
  data?: Verse & unknown;
}
