/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type JourneyFeedResponseDataProgress = {
  /**
     * Capítulos lidos
     * @minimum 0
     */
  chaptersRead: number;
  /**
     * Capítulos restantes
     * @minimum 0
     */
  chaptersRemaining: number;
  /**
     * Total de capítulos
     * @exclusiveMinimum 0
     */
  totalChapters: number;
  /**
     * Porcentagem concluída
     * @minimum 0
     * @maximum 100
     */
  percentComplete: number;
  /** Se chegou ao fim da Bíblia */
  isAtEnd: boolean;
};
