/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

export type JourneyFeedResponseDataNextItemsItemBook = {
  /** ID do livro */
  id: string;
  /**
     * Ordem canônica do livro (1-73)
     * @exclusiveMinimum 0
     */
  order: number;
  /** Nome do livro */
  name: string;
  /** Slug do livro */
  slug: string;
};
