/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { JourneyNextProgressResponseData } from './journeyNextProgressResponseData';
import type { PaginationViewModel } from './paginationViewModel';

/**
 * Resposta de sucesso para JourneyNextProgressResponse
 */
export interface JourneyNextProgressResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  /** Dados da resposta */
  data?: JourneyNextProgressResponseData;
  pagination?: PaginationViewModel;
}
