/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */

/**
 * Payload para solicitar um magic link
 */
export interface SendMagicLinkBody {
  /** E-mail do usuário */
  email: string;
}
