/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { UpdatedUserData } from './updatedUserData';

/**
 * Resposta de sucesso para UpdateAuthenticatedUserResponse
 */
export interface UpdateAuthenticatedUserResponse {
  /** Indica se a requisição foi bem-sucedida */
  success?: boolean;
  /** Mensagem opcional de contexto */
  message?: string;
  data?: UpdatedUserData;
}
