/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import type { User } from './user';

/**
 * Usuário autenticado atualizado com sucesso
 */
export interface UpdateAuthenticatedUserResponse {
  user: User;
}
