/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponse,
  GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams,
  GetApiV1PublicBibleBooksDynamicIdChaptersParams,
  GetApiV1PublicBibleBooksParams,
  GetBookByDynamicIdResponse,
  GetBooksResponse,
  GetChapterResponse,
  GetChaptersResponse,
  GetVerseResponse,
  GetVersesResponse
} from '../schemas';





export type getApiV1PublicBibleBooksResponse200 = {
  data: GetBooksResponse
  status: 200
}

export type getApiV1PublicBibleBooksResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksResponseSuccess = (getApiV1PublicBibleBooksResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksResponseError = (getApiV1PublicBibleBooksResponse400 | getApiV1PublicBibleBooksResponse429 | getApiV1PublicBibleBooksResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksResponse = (getApiV1PublicBibleBooksResponseSuccess | getApiV1PublicBibleBooksResponseError)

export const getGetApiV1PublicBibleBooksUrl = (params?: GetApiV1PublicBibleBooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/public/bible/books?${stringifiedParams}` : `/api/v1/public/bible/books`
}

/**
 * Retorna uma lista paginada de todos os livros da Bíblia, com informações como nome, slug, testamento e número de capítulos.
 * @summary Listar livros da Bíblia
 */
export const getApiV1PublicBibleBooks = async (params?: GetApiV1PublicBibleBooksParams, options?: RequestInit): Promise<getApiV1PublicBibleBooksResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksResponse
}





export const getGetApiV1PublicBibleBooksQueryKey = (params?: GetApiV1PublicBibleBooksParams,) => {
    return [
    `/api/v1/public/bible/books`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1PublicBibleBooksQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError = ApiErrorResponse>(params?: GetApiV1PublicBibleBooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>> = ({ signal }) => getApiV1PublicBibleBooks(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>>
export type GetApiV1PublicBibleBooksQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooks<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError = ApiErrorResponse>(
 params: undefined |  GetApiV1PublicBibleBooksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooks<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError = ApiErrorResponse>(
 params?: GetApiV1PublicBibleBooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooks<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError = ApiErrorResponse>(
 params?: GetApiV1PublicBibleBooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar livros da Bíblia
 */

export function useGetApiV1PublicBibleBooks<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError = ApiErrorResponse>(
 params?: GetApiV1PublicBibleBooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApiV1PublicBibleBooksDynamicIdResponse200 = {
  data: GetBookByDynamicIdResponse
  status: 200
}

export type getApiV1PublicBibleBooksDynamicIdResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksDynamicIdResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1PublicBibleBooksDynamicIdResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksDynamicIdResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksDynamicIdResponseSuccess = (getApiV1PublicBibleBooksDynamicIdResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksDynamicIdResponseError = (getApiV1PublicBibleBooksDynamicIdResponse400 | getApiV1PublicBibleBooksDynamicIdResponse404 | getApiV1PublicBibleBooksDynamicIdResponse429 | getApiV1PublicBibleBooksDynamicIdResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksDynamicIdResponse = (getApiV1PublicBibleBooksDynamicIdResponseSuccess | getApiV1PublicBibleBooksDynamicIdResponseError)

export const getGetApiV1PublicBibleBooksDynamicIdUrl = (dynamicId: string,) => {




  return `/api/v1/public/bible/books/${dynamicId}`
}

/**
 * Retorna um livro específico da Bíblia baseado em seu slug (ex: 'genesis') ou nome (ex: 'Gênesis').
 * @summary Obter livro por slug ou nome
 */
export const getApiV1PublicBibleBooksDynamicId = async (dynamicId: string, options?: RequestInit): Promise<getApiV1PublicBibleBooksDynamicIdResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksDynamicIdUrl(dynamicId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksDynamicIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksDynamicIdResponse
}





export const getGetApiV1PublicBibleBooksDynamicIdQueryKey = (dynamicId: string,) => {
    return [
    `/api/v1/public/bible/books/${dynamicId}`
    ] as const;
    }


export const getGetApiV1PublicBibleBooksDynamicIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError = ApiErrorResponse>(dynamicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksDynamicIdQueryKey(dynamicId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>> = ({ signal }) => getApiV1PublicBibleBooksDynamicId(dynamicId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: dynamicId !== null && dynamicId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksDynamicIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>>
export type GetApiV1PublicBibleBooksDynamicIdQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooksDynamicId<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError = ApiErrorResponse>(
 dynamicId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicId<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError = ApiErrorResponse>(
 dynamicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicId<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError = ApiErrorResponse>(
 dynamicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter livro por slug ou nome
 */

export function useGetApiV1PublicBibleBooksDynamicId<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError = ApiErrorResponse>(
 dynamicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksDynamicIdQueryOptions(dynamicId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApiV1PublicBibleBooksDynamicIdChaptersResponse200 = {
  data: GetChaptersResponse
  status: 200
}

export type getApiV1PublicBibleBooksDynamicIdChaptersResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksDynamicIdChaptersResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1PublicBibleBooksDynamicIdChaptersResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksDynamicIdChaptersResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksDynamicIdChaptersResponseSuccess = (getApiV1PublicBibleBooksDynamicIdChaptersResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksDynamicIdChaptersResponseError = (getApiV1PublicBibleBooksDynamicIdChaptersResponse400 | getApiV1PublicBibleBooksDynamicIdChaptersResponse404 | getApiV1PublicBibleBooksDynamicIdChaptersResponse429 | getApiV1PublicBibleBooksDynamicIdChaptersResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksDynamicIdChaptersResponse = (getApiV1PublicBibleBooksDynamicIdChaptersResponseSuccess | getApiV1PublicBibleBooksDynamicIdChaptersResponseError)

export const getGetApiV1PublicBibleBooksDynamicIdChaptersUrl = (dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/public/bible/books/${dynamicId}/chapters?${stringifiedParams}` : `/api/v1/public/bible/books/${dynamicId}/chapters`
}

/**
 * Retorna uma lista paginada de todos os capítulos de um livro específico da Bíblia.
 * @summary Listar capítulos de um livro
 */
export const getApiV1PublicBibleBooksDynamicIdChapters = async (dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams, options?: RequestInit): Promise<getApiV1PublicBibleBooksDynamicIdChaptersResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksDynamicIdChaptersUrl(dynamicId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksDynamicIdChaptersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksDynamicIdChaptersResponse
}





export const getGetApiV1PublicBibleBooksDynamicIdChaptersQueryKey = (dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams,) => {
    return [
    `/api/v1/public/bible/books/${dynamicId}/chapters`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1PublicBibleBooksDynamicIdChaptersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError = ApiErrorResponse>(dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksDynamicIdChaptersQueryKey(dynamicId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>> = ({ signal }) => getApiV1PublicBibleBooksDynamicIdChapters(dynamicId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: dynamicId !== null && dynamicId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksDynamicIdChaptersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>>
export type GetApiV1PublicBibleBooksDynamicIdChaptersQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooksDynamicIdChapters<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError = ApiErrorResponse>(
 dynamicId: string,
    params: undefined |  GetApiV1PublicBibleBooksDynamicIdChaptersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChapters<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError = ApiErrorResponse>(
 dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChapters<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError = ApiErrorResponse>(
 dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar capítulos de um livro
 */

export function useGetApiV1PublicBibleBooksDynamicIdChapters<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError = ApiErrorResponse>(
 dynamicId: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChapters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksDynamicIdChaptersQueryOptions(dynamicId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse200 = {
  data: GetChapterResponse
  status: 200
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseSuccess = (getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseError = (getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse400 | getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse404 | getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse429 | getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse = (getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseSuccess | getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseError)

export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberUrl = (dynamicId: string,
    number: string,) => {




  return `/api/v1/public/bible/books/${dynamicId}/chapters/${number}`
}

/**
 * Retorna um capítulo específico de um livro da Bíblia, identificado pelo slug/nome do livro e número do capítulo.
 * @summary Obter capítulo por número
 */
export const getApiV1PublicBibleBooksDynamicIdChaptersNumber = async (dynamicId: string,
    number: string, options?: RequestInit): Promise<getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksDynamicIdChaptersNumberUrl(dynamicId,number),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksDynamicIdChaptersNumberResponse
}





export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryKey = (dynamicId: string,
    number: string,) => {
    return [
    `/api/v1/public/bible/books/${dynamicId}/chapters/${number}`
    ] as const;
    }


export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError = ApiErrorResponse>(dynamicId: string,
    number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryKey(dynamicId,number);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>> = ({ signal }) => getApiV1PublicBibleBooksDynamicIdChaptersNumber(dynamicId,number, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: dynamicId !== null && dynamicId !== undefined && number !== null && number !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>>
export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumber<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumber<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumber<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter capítulo por número
 */

export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumber<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumber>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksDynamicIdChaptersNumberQueryOptions(dynamicId,number,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse200 = {
  data: GetVersesResponse
  status: 200
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseSuccess = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseError = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse400 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse404 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse429 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseSuccess | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseError)

export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesUrl = (dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/public/bible/books/${dynamicId}/chapters/${number}/verses?${stringifiedParams}` : `/api/v1/public/bible/books/${dynamicId}/chapters/${number}/verses`
}

/**
 * Retorna uma lista paginada de todos os versículos de um capítulo específico da Bíblia.
 * @summary Listar versículos de um capítulo
 */
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses = async (dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options?: RequestInit): Promise<getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesUrl(dynamicId,number,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse
}





export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryKey = (dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams,) => {
    return [
    `/api/v1/public/bible/books/${dynamicId}/chapters/${number}/verses`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError = ApiErrorResponse>(dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryKey(dynamicId,number,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>> = ({ signal }) => getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses(dynamicId,number,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: dynamicId !== null && dynamicId !== undefined && number !== null && number !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>>
export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVerses<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    params: undefined |  GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVerses<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVerses<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar versículos de um capítulo
 */

export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVerses<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    params?: GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVerses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryOptions(dynamicId,number,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse200 = {
  data: GetVerseResponse
  status: 200
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse429 = {
  data: ApiErrorResponse
  status: 429
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseSuccess = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse200) & {
  headers: Headers;
};
export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseError = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse400 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse404 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse429 | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse500) & {
  headers: Headers;
};

export type getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse = (getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseSuccess | getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseError)

export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseUrl = (dynamicId: string,
    number: string,
    verse: string,) => {




  return `/api/v1/public/bible/books/${dynamicId}/chapters/${number}/verses/${verse}`
}

/**
 * Retorna um versículo específico de um capítulo da Bíblia, identificado pelo slug/nome do livro, número do capítulo e número do versículo.
 * @summary Obter versículo por número
 */
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse = async (dynamicId: string,
    number: string,
    verse: string, options?: RequestInit): Promise<getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse> => {

  const res = await fetch(getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseUrl(dynamicId,number,verse),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse
}





export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryKey = (dynamicId: string,
    number: string,
    verse: string,) => {
    return [
    `/api/v1/public/bible/books/${dynamicId}/chapters/${number}/verses/${verse}`
    ] as const;
    }


export const getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError = ApiErrorResponse>(dynamicId: string,
    number: string,
    verse: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryKey(dynamicId,number,verse);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>> = ({ signal }) => getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse(dynamicId,number,verse, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: dynamicId !== null && dynamicId !== undefined && number !== null && number !== undefined && verse !== null && verse !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>>
export type GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryError = ApiErrorResponse


export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    verse: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    verse: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    verse: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obter versículo por número
 */

export function useGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse<TData = Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError = ApiErrorResponse>(
 dynamicId: string,
    number: string,
    verse: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerse>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseQueryOptions(dynamicId,number,verse,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






