/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponse,
  DiscoveryMarkVersesResponse,
  DiscoveryNextVersesResponse,
  DiscoveryStatsResponse,
  GetApiV1ReadingsDiscoveryNextParams,
  PostApiV1ReadingsDiscoveryBody
} from '../schemas';





export type getApiV1ReadingsDiscoveryNextResponse200 = {
  data: DiscoveryNextVersesResponse
  status: 200
}

export type getApiV1ReadingsDiscoveryNextResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getApiV1ReadingsDiscoveryNextResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1ReadingsDiscoveryNextResponseSuccess = (getApiV1ReadingsDiscoveryNextResponse200) & {
  headers: Headers;
};
export type getApiV1ReadingsDiscoveryNextResponseError = (getApiV1ReadingsDiscoveryNextResponse401 | getApiV1ReadingsDiscoveryNextResponse500) & {
  headers: Headers;
};

export type getApiV1ReadingsDiscoveryNextResponse = (getApiV1ReadingsDiscoveryNextResponseSuccess | getApiV1ReadingsDiscoveryNextResponseError)

export const getGetApiV1ReadingsDiscoveryNextUrl = (params?: GetApiV1ReadingsDiscoveryNextParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/readings/discovery/next?${stringifiedParams}` : `/api/v1/readings/discovery/next`
}

/**
 * Retorna todos os versículos de um capítulo para leitura no modo Discovery.
 * @summary Versículos do capítulo
 */
export const getApiV1ReadingsDiscoveryNext = async (params?: GetApiV1ReadingsDiscoveryNextParams, options?: RequestInit): Promise<getApiV1ReadingsDiscoveryNextResponse> => {

  const res = await fetch(getGetApiV1ReadingsDiscoveryNextUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1ReadingsDiscoveryNextResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1ReadingsDiscoveryNextResponse
}





export const getGetApiV1ReadingsDiscoveryNextQueryKey = (params?: GetApiV1ReadingsDiscoveryNextParams,) => {
    return [
    `/api/v1/readings/discovery/next`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1ReadingsDiscoveryNextQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError = ApiErrorResponse>(params?: GetApiV1ReadingsDiscoveryNextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ReadingsDiscoveryNextQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>> = ({ signal }) => getApiV1ReadingsDiscoveryNext(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ReadingsDiscoveryNextQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>>
export type GetApiV1ReadingsDiscoveryNextQueryError = ApiErrorResponse


export function useGetApiV1ReadingsDiscoveryNext<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError = ApiErrorResponse>(
 params: undefined |  GetApiV1ReadingsDiscoveryNextParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ReadingsDiscoveryNext<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError = ApiErrorResponse>(
 params?: GetApiV1ReadingsDiscoveryNextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ReadingsDiscoveryNext<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError = ApiErrorResponse>(
 params?: GetApiV1ReadingsDiscoveryNextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Versículos do capítulo
 */

export function useGetApiV1ReadingsDiscoveryNext<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError = ApiErrorResponse>(
 params?: GetApiV1ReadingsDiscoveryNextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryNext>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ReadingsDiscoveryNextQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postApiV1ReadingsDiscoveryResponse200 = {
  data: DiscoveryMarkVersesResponse
  status: 200
}

export type postApiV1ReadingsDiscoveryResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type postApiV1ReadingsDiscoveryResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type postApiV1ReadingsDiscoveryResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type postApiV1ReadingsDiscoveryResponseSuccess = (postApiV1ReadingsDiscoveryResponse200) & {
  headers: Headers;
};
export type postApiV1ReadingsDiscoveryResponseError = (postApiV1ReadingsDiscoveryResponse400 | postApiV1ReadingsDiscoveryResponse401 | postApiV1ReadingsDiscoveryResponse500) & {
  headers: Headers;
};

export type postApiV1ReadingsDiscoveryResponse = (postApiV1ReadingsDiscoveryResponseSuccess | postApiV1ReadingsDiscoveryResponseError)

export const getPostApiV1ReadingsDiscoveryUrl = () => {




  return `/api/v1/readings/discovery`
}

/**
 * Registra que o usuário leu versículos específicos.
 * @summary Marcar versículos como lidos
 */
export const postApiV1ReadingsDiscovery = async (postApiV1ReadingsDiscoveryBody?: PostApiV1ReadingsDiscoveryBody, options?: RequestInit): Promise<postApiV1ReadingsDiscoveryResponse> => {

  const res = await fetch(getPostApiV1ReadingsDiscoveryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1ReadingsDiscoveryBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1ReadingsDiscoveryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1ReadingsDiscoveryResponse
}




export const getPostApiV1ReadingsDiscoveryMutationOptions = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>, TError,{data?: PostApiV1ReadingsDiscoveryBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>, TError,{data?: PostApiV1ReadingsDiscoveryBody}, TContext> => {

const mutationKey = ['postApiV1ReadingsDiscovery'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>, {data?: PostApiV1ReadingsDiscoveryBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ReadingsDiscovery(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ReadingsDiscoveryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>>
    export type PostApiV1ReadingsDiscoveryMutationBody = PostApiV1ReadingsDiscoveryBody | undefined
    export type PostApiV1ReadingsDiscoveryMutationError = ApiErrorResponse

    /**
 * @summary Marcar versículos como lidos
 */
export const usePostApiV1ReadingsDiscovery = <TError = ApiErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>, TError,{data?: PostApiV1ReadingsDiscoveryBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ReadingsDiscovery>>,
        TError,
        {data?: PostApiV1ReadingsDiscoveryBody},
        TContext
      > => {
      return useMutation(getPostApiV1ReadingsDiscoveryMutationOptions(options), queryClient);
    }
    export type getApiV1ReadingsDiscoveryStatsResponse200 = {
  data: DiscoveryStatsResponse
  status: 200
}

export type getApiV1ReadingsDiscoveryStatsResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getApiV1ReadingsDiscoveryStatsResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getApiV1ReadingsDiscoveryStatsResponseSuccess = (getApiV1ReadingsDiscoveryStatsResponse200) & {
  headers: Headers;
};
export type getApiV1ReadingsDiscoveryStatsResponseError = (getApiV1ReadingsDiscoveryStatsResponse401 | getApiV1ReadingsDiscoveryStatsResponse500) & {
  headers: Headers;
};

export type getApiV1ReadingsDiscoveryStatsResponse = (getApiV1ReadingsDiscoveryStatsResponseSuccess | getApiV1ReadingsDiscoveryStatsResponseError)

export const getGetApiV1ReadingsDiscoveryStatsUrl = () => {




  return `/api/v1/readings/discovery/stats`
}

/**
 * Retorna estatísticas de leitura no modo Discovery.
 * @summary Estatísticas do Discovery
 */
export const getApiV1ReadingsDiscoveryStats = async ( options?: RequestInit): Promise<getApiV1ReadingsDiscoveryStatsResponse> => {

  const res = await fetch(getGetApiV1ReadingsDiscoveryStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1ReadingsDiscoveryStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1ReadingsDiscoveryStatsResponse
}





export const getGetApiV1ReadingsDiscoveryStatsQueryKey = () => {
    return [
    `/api/v1/readings/discovery/stats`
    ] as const;
    }


export const getGetApiV1ReadingsDiscoveryStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError = ApiErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ReadingsDiscoveryStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>> = ({ signal }) => getApiV1ReadingsDiscoveryStats({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ReadingsDiscoveryStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>>
export type GetApiV1ReadingsDiscoveryStatsQueryError = ApiErrorResponse


export function useGetApiV1ReadingsDiscoveryStats<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError = ApiErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ReadingsDiscoveryStats<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ReadingsDiscoveryStats<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Estatísticas do Discovery
 */

export function useGetApiV1ReadingsDiscoveryStats<TData = Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ReadingsDiscoveryStats>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ReadingsDiscoveryStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






