export type BibleBookEntry = {
  slug: string;
  testament: "OLD" | "NEW";
};

export const BASE_RAW_URL =
  "https://raw.githubusercontent.com/Dancrf/biblia-db/refs/heads/main";

export const EXPECTED_BOOK_COUNT = 73;

export const BIBLE_BOOKS: BibleBookEntry[] = [
  // Antigo Testamento (46)
  { slug: "1ma", testament: "OLD" },
  { slug: "1pa", testament: "OLD" },
  { slug: "1rs", testament: "OLD" },
  { slug: "1sm", testament: "OLD" },
  { slug: "2ma", testament: "OLD" },
  { slug: "2pa", testament: "OLD" },
  { slug: "2rs", testament: "OLD" },
  { slug: "2sm", testament: "OLD" },
  { slug: "ab", testament: "OLD" },
  { slug: "ag", testament: "OLD" },
  { slug: "am", testament: "OLD" },
  { slug: "ba", testament: "OLD" },
  { slug: "cc", testament: "OLD" },
  { slug: "dn", testament: "OLD" },
  { slug: "dt", testament: "OLD" },
  { slug: "ees", testament: "OLD" },
  { slug: "esd", testament: "OLD" },
  { slug: "est", testament: "OLD" },
  { slug: "eus", testament: "OLD" },
  { slug: "ex", testament: "OLD" },
  { slug: "ez", testament: "OLD" },
  { slug: "gn", testament: "OLD" },
  { slug: "hc", testament: "OLD" },
  { slug: "is", testament: "OLD" },
  { slug: "jdi", testament: "OLD" },
  { slug: "je", testament: "OLD" },
  { slug: "jl", testament: "OLD" },
  { slug: "jn", testament: "OLD" },
  { slug: "job", testament: "OLD" },
  { slug: "js", testament: "OLD" },
  { slug: "ju", testament: "OLD" },
  { slug: "lm", testament: "OLD" },
  { slug: "lv", testament: "OLD" },
  { slug: "mic", testament: "OLD" },
  { slug: "ml", testament: "OLD" },
  { slug: "na", testament: "OLD" },
  { slug: "ne", testament: "OLD" },
  { slug: "nm", testament: "OLD" },
  { slug: "os", testament: "OLD" },
  { slug: "ps", testament: "OLD" },
  { slug: "pv", testament: "OLD" },
  { slug: "rt", testament: "OLD" },
  { slug: "sa", testament: "OLD" },
  { slug: "so", testament: "OLD" },
  { slug: "tob", testament: "OLD" },
  { slug: "zc", testament: "OLD" },
  // Novo Testamento (27)
  { slug: "1co", testament: "NEW" },
  { slug: "1jo", testament: "NEW" },
  { slug: "1pe", testament: "NEW" },
  { slug: "1tm", testament: "NEW" },
  { slug: "1ts", testament: "NEW" },
  { slug: "2co", testament: "NEW" },
  { slug: "2jo", testament: "NEW" },
  { slug: "2pe", testament: "NEW" },
  { slug: "2tm", testament: "NEW" },
  { slug: "2ts", testament: "NEW" },
  { slug: "3jo", testament: "NEW" },
  { slug: "act", testament: "NEW" },
  { slug: "ap", testament: "NEW" },
  { slug: "cl", testament: "NEW" },
  { slug: "ef", testament: "NEW" },
  { slug: "fm", testament: "NEW" },
  { slug: "fp", testament: "NEW" },
  { slug: "gl", testament: "NEW" },
  { slug: "hb", testament: "NEW" },
  { slug: "jda", testament: "NEW" },
  { slug: "jo", testament: "NEW" },
  { slug: "lc", testament: "NEW" },
  { slug: "mc", testament: "NEW" },
  { slug: "mt", testament: "NEW" },
  { slug: "rm", testament: "NEW" },
  { slug: "tg", testament: "NEW" },
  { slug: "tt", testament: "NEW" },
];
