/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import * as zod from 'zod';


/**
 * Cria um novo perfil para o usuário autenticado.
 * @summary Criar perfil do usuário autenticado
 */
export const postApiV1ProfilesMeBodyUsernameMin = 3;
export const postApiV1ProfilesMeBodyUsernameMax = 50;


export const postApiV1ProfilesMeBodyUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');
export const postApiV1ProfilesMeBodyNameMax = 100;

export const postApiV1ProfilesMeBodyBioMax = 500;

export const postApiV1ProfilesMeBodyPictureUrlMax = 500;



export const PostApiV1ProfilesMeBody = zod.object({
  "username": zod.string().min(postApiV1ProfilesMeBodyUsernameMin).max(postApiV1ProfilesMeBodyUsernameMax).regex(postApiV1ProfilesMeBodyUsernameRegExp).describe('Username único'),
  "name": zod.string().min(1).max(postApiV1ProfilesMeBodyNameMax).describe('Nome de exibição'),
  "bio": zod.string().max(postApiV1ProfilesMeBodyBioMax).nullish().describe('Biografia do usuário'),
  "pictureUrl": zod.url().max(postApiV1ProfilesMeBodyPictureUrlMax).nullish().describe('URL da foto de perfil')
}).describe('Payload para criar o perfil do usuário')

/**
 * Retorna os dados do perfil do usuário autenticado.
 * @summary Obter perfil do usuário autenticado
 */
export const getApiV1ProfilesMeResponseProfileUsernameMin = 3;
export const getApiV1ProfilesMeResponseProfileUsernameMax = 50;


export const getApiV1ProfilesMeResponseProfileUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');
export const getApiV1ProfilesMeResponseProfileNameMax = 100;

export const getApiV1ProfilesMeResponseProfileBioMax = 500;

export const getApiV1ProfilesMeResponseProfilePictureUrlMax = 500;



export const GetApiV1ProfilesMeResponse = zod.object({
  "profile": zod.object({
  "username": zod.string().min(getApiV1ProfilesMeResponseProfileUsernameMin).max(getApiV1ProfilesMeResponseProfileUsernameMax).regex(getApiV1ProfilesMeResponseProfileUsernameRegExp).describe('Username único'),
  "name": zod.string().min(1).max(getApiV1ProfilesMeResponseProfileNameMax).describe('Nome de exibição'),
  "bio": zod.string().max(getApiV1ProfilesMeResponseProfileBioMax).nullish().describe('Biografia do usuário'),
  "pictureUrl": zod.url().max(getApiV1ProfilesMeResponseProfilePictureUrlMax).nullish().describe('URL da foto de perfil')
}).describe('Representação pública do perfil')
}).describe('Perfil do usuário autenticado')

/**
 * Atualiza os dados do perfil do usuário autenticado.
 * @summary Atualizar perfil do usuário autenticado
 */
export const patchApiV1ProfilesMeBodyUsernameMin = 3;
export const patchApiV1ProfilesMeBodyUsernameMax = 50;


export const patchApiV1ProfilesMeBodyUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');
export const patchApiV1ProfilesMeBodyNameMax = 100;

export const patchApiV1ProfilesMeBodyBioMax = 500;

export const patchApiV1ProfilesMeBodyPictureUrlMax = 500;



export const PatchApiV1ProfilesMeBody = zod.object({
  "username": zod.string().min(patchApiV1ProfilesMeBodyUsernameMin).max(patchApiV1ProfilesMeBodyUsernameMax).regex(patchApiV1ProfilesMeBodyUsernameRegExp).optional().describe('Username único'),
  "name": zod.string().min(1).max(patchApiV1ProfilesMeBodyNameMax).optional().describe('Nome de exibição'),
  "bio": zod.string().max(patchApiV1ProfilesMeBodyBioMax).nullish().describe('Biografia do usuário'),
  "pictureUrl": zod.url().max(patchApiV1ProfilesMeBodyPictureUrlMax).nullish().describe('URL da foto de perfil')
}).describe('Payload para atualizar o perfil do usuário autenticado')

export const patchApiV1ProfilesMeResponseProfileUsernameMin = 3;
export const patchApiV1ProfilesMeResponseProfileUsernameMax = 50;


export const patchApiV1ProfilesMeResponseProfileUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');
export const patchApiV1ProfilesMeResponseProfileNameMax = 100;

export const patchApiV1ProfilesMeResponseProfileBioMax = 500;

export const patchApiV1ProfilesMeResponseProfilePictureUrlMax = 500;



export const PatchApiV1ProfilesMeResponse = zod.object({
  "profile": zod.object({
  "username": zod.string().min(patchApiV1ProfilesMeResponseProfileUsernameMin).max(patchApiV1ProfilesMeResponseProfileUsernameMax).regex(patchApiV1ProfilesMeResponseProfileUsernameRegExp).describe('Username único'),
  "name": zod.string().min(1).max(patchApiV1ProfilesMeResponseProfileNameMax).describe('Nome de exibição'),
  "bio": zod.string().max(patchApiV1ProfilesMeResponseProfileBioMax).nullish().describe('Biografia do usuário'),
  "pictureUrl": zod.url().max(patchApiV1ProfilesMeResponseProfilePictureUrlMax).nullish().describe('URL da foto de perfil')
}).describe('Representação pública do perfil')
}).describe('Perfil atualizado com sucesso')

/**
 * Retorna os dados públicos de um perfil pelo username.
 * @summary Obter perfil por username
 */
export const getApiV1ProfilesUsernamePathUsernameMax = 50;


export const getApiV1ProfilesUsernamePathUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');


export const GetApiV1ProfilesUsernameParams = zod.object({
  "username": zod.string().min(1).max(getApiV1ProfilesUsernamePathUsernameMax).regex(getApiV1ProfilesUsernamePathUsernameRegExp).describe('Username')
})

export const getApiV1ProfilesUsernameResponseUsernameMin = 3;
export const getApiV1ProfilesUsernameResponseUsernameMax = 50;


export const getApiV1ProfilesUsernameResponseUsernameRegExp = new RegExp('^[a-zA-Z0-9_]+$');
export const getApiV1ProfilesUsernameResponseNameMax = 100;

export const getApiV1ProfilesUsernameResponseBioMax = 500;

export const getApiV1ProfilesUsernameResponsePictureUrlMax = 500;



export const GetApiV1ProfilesUsernameResponse = zod.object({
  "username": zod.string().min(getApiV1ProfilesUsernameResponseUsernameMin).max(getApiV1ProfilesUsernameResponseUsernameMax).regex(getApiV1ProfilesUsernameResponseUsernameRegExp).describe('Username único'),
  "name": zod.string().min(1).max(getApiV1ProfilesUsernameResponseNameMax).describe('Nome de exibição'),
  "bio": zod.string().max(getApiV1ProfilesUsernameResponseBioMax).nullish().describe('Biografia do usuário'),
  "pictureUrl": zod.url().max(getApiV1ProfilesUsernameResponsePictureUrlMax).nullish().describe('URL da foto de perfil')
}).describe('Representação pública do perfil')

