/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import * as zod from "zod";

/**
 * Cria um novo perfil para o usuário autenticado.
 * @summary Criar perfil do usuário autenticado
 */
export const postApiV1ProfilesMeBodyUsernameMin = 3;
export const postApiV1ProfilesMeBodyUsernameMax = 50;

export const postApiV1ProfilesMeBodyUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const postApiV1ProfilesMeBodyNameMax = 100;

export const postApiV1ProfilesMeBodyBioMax = 500;

export const postApiV1ProfilesMeBodyPictureUrlMax = 500;

export const PostApiV1ProfilesMeBody = zod
  .object({
    username: zod
      .string()
      .min(postApiV1ProfilesMeBodyUsernameMin)
      .max(postApiV1ProfilesMeBodyUsernameMax)
      .regex(postApiV1ProfilesMeBodyUsernameRegExp)
      .describe("Username único"),
    name: zod
      .string()
      .min(1)
      .max(postApiV1ProfilesMeBodyNameMax)
      .describe("Nome de exibição"),
    bio: zod
      .string()
      .max(postApiV1ProfilesMeBodyBioMax)
      .nullish()
      .describe("Biografia do usuário"),
    pictureUrl: zod
      .url()
      .max(postApiV1ProfilesMeBodyPictureUrlMax)
      .nullish()
      .describe("URL da foto de perfil"),
  })
  .describe("Payload para criar o perfil do usuário");

/**
 * Retorna os dados do perfil do usuário autenticado.
 * @summary Obter perfil do usuário autenticado
 */
export const getApiV1ProfilesMeResponseSuccessDefault = true;
export const getApiV1ProfilesMeResponseDataUsernameMin = 3;
export const getApiV1ProfilesMeResponseDataUsernameMax = 50;

export const getApiV1ProfilesMeResponseDataUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const getApiV1ProfilesMeResponseDataNameMax = 100;

export const getApiV1ProfilesMeResponseDataBioMax = 500;

export const getApiV1ProfilesMeResponseDataPictureUrlMax = 500;

export const GetApiV1ProfilesMeResponse = zod
  .object({
    success: zod
      .boolean()
      .default(getApiV1ProfilesMeResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        id: zod.uuid().describe("ID único do perfil"),
        userId: zod.uuid().describe("ID do usuário"),
        username: zod
          .string()
          .min(getApiV1ProfilesMeResponseDataUsernameMin)
          .max(getApiV1ProfilesMeResponseDataUsernameMax)
          .regex(getApiV1ProfilesMeResponseDataUsernameRegExp)
          .describe("Username único"),
        name: zod
          .string()
          .min(1)
          .max(getApiV1ProfilesMeResponseDataNameMax)
          .describe("Nome de exibição"),
        bio: zod
          .string()
          .max(getApiV1ProfilesMeResponseDataBioMax)
          .nullish()
          .describe("Biografia do usuário"),
        pictureUrl: zod
          .url()
          .max(getApiV1ProfilesMeResponseDataPictureUrlMax)
          .nullish()
          .describe("URL da foto de perfil"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de criação"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de atualização"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para GetAuthenticatedProfileResponse");

/**
 * Atualiza os dados do perfil do usuário autenticado.
 * @summary Atualizar perfil do usuário autenticado
 */
export const patchApiV1ProfilesMeBodyUsernameMin = 3;
export const patchApiV1ProfilesMeBodyUsernameMax = 50;

export const patchApiV1ProfilesMeBodyUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const patchApiV1ProfilesMeBodyNameMax = 100;

export const patchApiV1ProfilesMeBodyBioMax = 500;

export const patchApiV1ProfilesMeBodyPictureUrlMax = 500;

export const PatchApiV1ProfilesMeBody = zod
  .object({
    username: zod
      .string()
      .min(patchApiV1ProfilesMeBodyUsernameMin)
      .max(patchApiV1ProfilesMeBodyUsernameMax)
      .regex(patchApiV1ProfilesMeBodyUsernameRegExp)
      .optional()
      .describe("Username único"),
    name: zod
      .string()
      .min(1)
      .max(patchApiV1ProfilesMeBodyNameMax)
      .optional()
      .describe("Nome de exibição"),
    bio: zod
      .string()
      .max(patchApiV1ProfilesMeBodyBioMax)
      .nullish()
      .describe("Biografia do usuário"),
    pictureUrl: zod
      .url()
      .max(patchApiV1ProfilesMeBodyPictureUrlMax)
      .nullish()
      .describe("URL da foto de perfil"),
  })
  .describe("Payload para atualizar o perfil do usuário autenticado");

export const patchApiV1ProfilesMeResponseSuccessDefault = true;
export const patchApiV1ProfilesMeResponseDataUsernameMin = 3;
export const patchApiV1ProfilesMeResponseDataUsernameMax = 50;

export const patchApiV1ProfilesMeResponseDataUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const patchApiV1ProfilesMeResponseDataNameMax = 100;

export const patchApiV1ProfilesMeResponseDataBioMax = 500;

export const patchApiV1ProfilesMeResponseDataPictureUrlMax = 500;

export const PatchApiV1ProfilesMeResponse = zod
  .object({
    success: zod
      .boolean()
      .default(patchApiV1ProfilesMeResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        id: zod.uuid().describe("ID único do perfil"),
        userId: zod.uuid().describe("ID do usuário"),
        username: zod
          .string()
          .min(patchApiV1ProfilesMeResponseDataUsernameMin)
          .max(patchApiV1ProfilesMeResponseDataUsernameMax)
          .regex(patchApiV1ProfilesMeResponseDataUsernameRegExp)
          .describe("Username único"),
        name: zod
          .string()
          .min(1)
          .max(patchApiV1ProfilesMeResponseDataNameMax)
          .describe("Nome de exibição"),
        bio: zod
          .string()
          .max(patchApiV1ProfilesMeResponseDataBioMax)
          .nullish()
          .describe("Biografia do usuário"),
        pictureUrl: zod
          .url()
          .max(patchApiV1ProfilesMeResponseDataPictureUrlMax)
          .nullish()
          .describe("URL da foto de perfil"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de criação"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de atualização"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para UpdateAuthenticatedProfileResponse");

/**
 * Retorna os dados públicos de um perfil pelo username.
 * @summary Obter perfil por username
 */
export const getApiV1ProfilesUsernamePathUsernameMax = 50;

export const getApiV1ProfilesUsernamePathUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);

export const GetApiV1ProfilesUsernameParams = zod.object({
  username: zod
    .string()
    .min(1)
    .max(getApiV1ProfilesUsernamePathUsernameMax)
    .regex(getApiV1ProfilesUsernamePathUsernameRegExp)
    .describe("Username"),
});

export const getApiV1ProfilesUsernameResponseSuccessDefault = true;
export const getApiV1ProfilesUsernameResponseDataUsernameMin = 3;
export const getApiV1ProfilesUsernameResponseDataUsernameMax = 50;

export const getApiV1ProfilesUsernameResponseDataUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const getApiV1ProfilesUsernameResponseDataNameMax = 100;

export const getApiV1ProfilesUsernameResponseDataBioMax = 500;

export const getApiV1ProfilesUsernameResponseDataPictureUrlMax = 500;

export const GetApiV1ProfilesUsernameResponse = zod
  .object({
    success: zod
      .boolean()
      .default(getApiV1ProfilesUsernameResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        id: zod.uuid().describe("ID único do perfil"),
        userId: zod.uuid().describe("ID do usuário"),
        username: zod
          .string()
          .min(getApiV1ProfilesUsernameResponseDataUsernameMin)
          .max(getApiV1ProfilesUsernameResponseDataUsernameMax)
          .regex(getApiV1ProfilesUsernameResponseDataUsernameRegExp)
          .describe("Username único"),
        name: zod
          .string()
          .min(1)
          .max(getApiV1ProfilesUsernameResponseDataNameMax)
          .describe("Nome de exibição"),
        bio: zod
          .string()
          .max(getApiV1ProfilesUsernameResponseDataBioMax)
          .nullish()
          .describe("Biografia do usuário"),
        pictureUrl: zod
          .url()
          .max(getApiV1ProfilesUsernameResponseDataPictureUrlMax)
          .nullish()
          .describe("URL da foto de perfil"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de criação"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de atualização"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para GetProfileByUsernameResponse");

/**
 * Verifica se um username está disponível para usar.
 * @summary Verificar disponibilidade de username
 */
export const getApiV1ProfilesCheckUsernameUsernamePathUsernameMax = 50;

export const getApiV1ProfilesCheckUsernameUsernamePathUsernameRegExp =
  new RegExp("^[a-zA-Z0-9_]+$");

export const GetApiV1ProfilesCheckUsernameUsernameParams = zod.object({
  username: zod
    .string()
    .min(1)
    .max(getApiV1ProfilesCheckUsernameUsernamePathUsernameMax)
    .regex(getApiV1ProfilesCheckUsernameUsernamePathUsernameRegExp)
    .describe("Username"),
});

export const getApiV1ProfilesCheckUsernameUsernameResponseSuccessDefault = true;

export const GetApiV1ProfilesCheckUsernameUsernameResponse = zod
  .object({
    success: zod
      .boolean()
      .default(getApiV1ProfilesCheckUsernameUsernameResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        available: zod.boolean().describe("Whether the username is available"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para CheckUsernameAvailabilityResponse");

/**
 * Faz upload de uma nova foto de perfil. Formatos: JPEG, PNG, WEBP. Tamanho máximo: 5MB.
 * @summary Upload de foto de perfil
 */
export const PostApiV1ProfilesMeAvatarBody = zod
  .object({
    file: zod.instanceof(File).optional(),
  })
  .describe("Multipart form data with profile picture file");

export const postApiV1ProfilesMeAvatarResponseSuccessDefault = true;
export const postApiV1ProfilesMeAvatarResponseDataUsernameMin = 3;
export const postApiV1ProfilesMeAvatarResponseDataUsernameMax = 50;

export const postApiV1ProfilesMeAvatarResponseDataUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const postApiV1ProfilesMeAvatarResponseDataNameMax = 100;

export const postApiV1ProfilesMeAvatarResponseDataBioMax = 500;

export const postApiV1ProfilesMeAvatarResponseDataPictureUrlMax = 500;

export const PostApiV1ProfilesMeAvatarResponse = zod
  .object({
    success: zod
      .boolean()
      .default(postApiV1ProfilesMeAvatarResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        id: zod.uuid().describe("ID único do perfil"),
        userId: zod.uuid().describe("ID do usuário"),
        username: zod
          .string()
          .min(postApiV1ProfilesMeAvatarResponseDataUsernameMin)
          .max(postApiV1ProfilesMeAvatarResponseDataUsernameMax)
          .regex(postApiV1ProfilesMeAvatarResponseDataUsernameRegExp)
          .describe("Username único"),
        name: zod
          .string()
          .min(1)
          .max(postApiV1ProfilesMeAvatarResponseDataNameMax)
          .describe("Nome de exibição"),
        bio: zod
          .string()
          .max(postApiV1ProfilesMeAvatarResponseDataBioMax)
          .nullish()
          .describe("Biografia do usuário"),
        pictureUrl: zod
          .url()
          .max(postApiV1ProfilesMeAvatarResponseDataPictureUrlMax)
          .nullish()
          .describe("URL da foto de perfil"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de criação"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de atualização"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para UpdateProfilePictureResponse");

/**
 * Remove a foto de perfil do usuário autenticado.
 * @summary Deletar foto de perfil
 */
export const deleteApiV1ProfilesMeAvatarResponseSuccessDefault = true;
export const deleteApiV1ProfilesMeAvatarResponseDataUsernameMin = 3;
export const deleteApiV1ProfilesMeAvatarResponseDataUsernameMax = 50;

export const deleteApiV1ProfilesMeAvatarResponseDataUsernameRegExp = new RegExp(
  "^[a-zA-Z0-9_]+$",
);
export const deleteApiV1ProfilesMeAvatarResponseDataNameMax = 100;

export const deleteApiV1ProfilesMeAvatarResponseDataBioMax = 500;

export const deleteApiV1ProfilesMeAvatarResponseDataPictureUrlMax = 500;

export const DeleteApiV1ProfilesMeAvatarResponse = zod
  .object({
    success: zod
      .boolean()
      .default(deleteApiV1ProfilesMeAvatarResponseSuccessDefault)
      .describe("Indica se a requisição foi bem-sucedida"),
    message: zod.string().describe("Mensagem de contexto da resposta"),
    code: zod.string().describe("Código da resposta"),
    data: zod
      .object({
        id: zod.uuid().describe("ID único do perfil"),
        userId: zod.uuid().describe("ID do usuário"),
        username: zod
          .string()
          .min(deleteApiV1ProfilesMeAvatarResponseDataUsernameMin)
          .max(deleteApiV1ProfilesMeAvatarResponseDataUsernameMax)
          .regex(deleteApiV1ProfilesMeAvatarResponseDataUsernameRegExp)
          .describe("Username único"),
        name: zod
          .string()
          .min(1)
          .max(deleteApiV1ProfilesMeAvatarResponseDataNameMax)
          .describe("Nome de exibição"),
        bio: zod
          .string()
          .max(deleteApiV1ProfilesMeAvatarResponseDataBioMax)
          .nullish()
          .describe("Biografia do usuário"),
        pictureUrl: zod
          .url()
          .max(deleteApiV1ProfilesMeAvatarResponseDataPictureUrlMax)
          .nullish()
          .describe("URL da foto de perfil"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de criação"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Data de atualização"),
      })
      .optional()
      .describe("Dados da resposta"),
  })
  .describe("Resposta de sucesso para DeleteAvatarResponse");
