/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Versum API
 * OpenAPI spec version: 1.3.2
 */
import * as zod from 'zod';


/**
 * Retorna uma lista paginada de todos os livros da Bíblia, com informações como nome, slug, testamento e número de capítulos.
 * @summary Listar livros da Bíblia
 */
export const getApiV1PublicBibleBooksQueryPageDefault = `1`;
export const getApiV1PublicBibleBooksQueryLimitDefault = `10`;

export const GetApiV1PublicBibleBooksQueryParams = zod.object({
  "page": zod.string().default(getApiV1PublicBibleBooksQueryPageDefault).describe('Número da página (padrão: 1)'),
  "limit": zod.string().default(getApiV1PublicBibleBooksQueryLimitDefault).describe('Limite de itens por página (padrão: 10)')
})

export const getApiV1PublicBibleBooksResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksResponseDataItemOrderExclusiveMin = 0;

export const getApiV1PublicBibleBooksResponseDataItemNameMax = 100;

export const getApiV1PublicBibleBooksResponseDataItemSlugMax = 10;

export const getApiV1PublicBibleBooksResponseDataItemNiceNameMax = 100;

export const getApiV1PublicBibleBooksResponseDataItemTotalChaptersExclusiveMin = 0;

export const getApiV1PublicBibleBooksResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.array(zod.object({
  "id": zod.uuid().describe('ID único do livro'),
  "order": zod.number().gt(getApiV1PublicBibleBooksResponseDataItemOrderExclusiveMin).describe('Ordem canônica do livro (1-73)'),
  "name": zod.string().max(getApiV1PublicBibleBooksResponseDataItemNameMax).describe('Nome do livro'),
  "slug": zod.string().max(getApiV1PublicBibleBooksResponseDataItemSlugMax).describe('Slug do livro'),
  "niceName": zod.string().max(getApiV1PublicBibleBooksResponseDataItemNiceNameMax).describe('Nome amigável do livro'),
  "testament": zod.enum(['OLD', 'NEW']).describe('Testamento ao qual o livro pertence'),
  "totalChapters": zod.number().gt(getApiV1PublicBibleBooksResponseDataItemTotalChaptersExclusiveMin).describe('Número total de capítulos')
}).describe('Livro da Bíblia')).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetBooksResponse')

/**
 * Retorna um livro específico da Bíblia baseado em seu slug (ex: 'genesis') ou nome (ex: 'Gênesis').
 * @summary Obter livro por slug ou nome
 */



export const GetApiV1PublicBibleBooksDynamicIdParams = zod.object({
  "dynamicId": zod.string().min(1).describe('Slug ou nome do livro (ex: \'genesis\' ou \'Gênesis\')')
})

export const getApiV1PublicBibleBooksDynamicIdResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksDynamicIdResponseDataOneOrderExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdResponseDataOneNameMax = 100;

export const getApiV1PublicBibleBooksDynamicIdResponseDataOneSlugMax = 10;

export const getApiV1PublicBibleBooksDynamicIdResponseDataOneNiceNameMax = 100;

export const getApiV1PublicBibleBooksDynamicIdResponseDataOneTotalChaptersExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksDynamicIdResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksDynamicIdResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksDynamicIdResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.object({
  "id": zod.uuid().describe('ID único do livro'),
  "order": zod.number().gt(getApiV1PublicBibleBooksDynamicIdResponseDataOneOrderExclusiveMin).describe('Ordem canônica do livro (1-73)'),
  "name": zod.string().max(getApiV1PublicBibleBooksDynamicIdResponseDataOneNameMax).describe('Nome do livro'),
  "slug": zod.string().max(getApiV1PublicBibleBooksDynamicIdResponseDataOneSlugMax).describe('Slug do livro'),
  "niceName": zod.string().max(getApiV1PublicBibleBooksDynamicIdResponseDataOneNiceNameMax).describe('Nome amigável do livro'),
  "testament": zod.enum(['OLD', 'NEW']).describe('Testamento ao qual o livro pertence'),
  "totalChapters": zod.number().gt(getApiV1PublicBibleBooksDynamicIdResponseDataOneTotalChaptersExclusiveMin).describe('Número total de capítulos')
}).describe('Livro da Bíblia').and(zod.unknown().describe('Dados da resposta')).optional(),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksDynamicIdResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksDynamicIdResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetBookByDynamicIdResponse')

/**
 * Retorna uma lista paginada de todos os capítulos de um livro específico da Bíblia.
 * @summary Listar capítulos de um livro
 */



export const GetApiV1PublicBibleBooksDynamicIdChaptersParams = zod.object({
  "dynamicId": zod.string().min(1).describe('Slug ou nome do livro (ex: \'genesis\' ou \'Gênesis\')')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersQueryPageDefault = `1`;
export const getApiV1PublicBibleBooksDynamicIdChaptersQueryLimitDefault = `10`;

export const GetApiV1PublicBibleBooksDynamicIdChaptersQueryParams = zod.object({
  "page": zod.string().default(getApiV1PublicBibleBooksDynamicIdChaptersQueryPageDefault).describe('Número da página (padrão: 1)'),
  "limit": zod.string().default(getApiV1PublicBibleBooksDynamicIdChaptersQueryLimitDefault).describe('Limite de itens por página (padrão: 10)')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksDynamicIdChaptersResponseDataItemNumberExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersResponseDataItemTotalVersesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksDynamicIdChaptersResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksDynamicIdChaptersResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.array(zod.object({
  "id": zod.uuid().describe('ID único do capítulo'),
  "bookId": zod.uuid().describe('ID do livro ao qual o capítulo pertence'),
  "number": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersResponseDataItemNumberExclusiveMin).describe('Número do capítulo'),
  "totalVerses": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersResponseDataItemTotalVersesExclusiveMin).describe('Número total de versículos')
}).describe('Capítulo de um livro da Bíblia')).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetChaptersResponse')

/**
 * Retorna um capítulo específico de um livro da Bíblia, identificado pelo slug/nome do livro e número do capítulo.
 * @summary Obter capítulo por número
 */

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberPathNumberRegExp = new RegExp('^\\d+$');


export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberParams = zod.object({
  "dynamicId": zod.string().min(1).describe('Slug ou nome do livro (ex: \'genesis\' ou \'Gênesis\')'),
  "number": zod.string().regex(getApiV1PublicBibleBooksDynamicIdChaptersNumberPathNumberRegExp).describe('Número do capítulo')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseDataOneNumberExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseDataOneTotalVersesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.object({
  "id": zod.uuid().describe('ID único do capítulo'),
  "bookId": zod.uuid().describe('ID do livro ao qual o capítulo pertence'),
  "number": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseDataOneNumberExclusiveMin).describe('Número do capítulo'),
  "totalVerses": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponseDataOneTotalVersesExclusiveMin).describe('Número total de versículos')
}).describe('Capítulo de um livro da Bíblia').and(zod.unknown().describe('Dados da resposta')).optional(),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetChapterResponse')

/**
 * Retorna uma lista paginada de todos os versículos de um capítulo específico da Bíblia.
 * @summary Listar versículos de um capítulo
 */

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesPathNumberRegExp = new RegExp('^\\d+$');


export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesParams = zod.object({
  "dynamicId": zod.string().min(1).describe('Slug ou nome do livro (ex: \'genesis\' ou \'Gênesis\')'),
  "number": zod.string().regex(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesPathNumberRegExp).describe('Número do capítulo')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryPageDefault = `1`;
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryLimitDefault = `10`;

export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryParams = zod.object({
  "page": zod.string().default(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryPageDefault).describe('Número da página (padrão: 1)'),
  "limit": zod.string().default(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesQueryLimitDefault).describe('Limite de itens por página (padrão: 10)')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseDataItemNumberExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.array(zod.object({
  "id": zod.uuid().describe('ID único do versículo'),
  "chapterId": zod.uuid().describe('ID do capítulo ao qual o versículo pertence'),
  "number": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponseDataItemNumberExclusiveMin).describe('Número do versículo'),
  "text": zod.string().describe('Texto do versículo')
}).describe('Versículo de um capítulo da Bíblia')).optional().describe('Dados da resposta'),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetVersesResponse')

/**
 * Retorna um versículo específico de um capítulo da Bíblia, identificado pelo slug/nome do livro, número do capítulo e número do versículo.
 * @summary Obter versículo por número
 */

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVersePathNumberRegExp = new RegExp('^\\d+$');
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVersePathVerseRegExp = new RegExp('^\\d+$');


export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseParams = zod.object({
  "dynamicId": zod.string().min(1).describe('Slug ou nome do livro (ex: \'genesis\' ou \'Gênesis\')'),
  "number": zod.string().regex(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVersePathNumberRegExp).describe('Número do capítulo'),
  "verse": zod.string().regex(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVersePathVerseRegExp).describe('Número do versículo')
})

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseSuccessDefault = true;
export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseDataOneNumberExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationCurrentPageExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationTotalPagesExclusiveMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationTotalItemsMin = 0;

export const getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationItemsPerPageExclusiveMin = 0;



export const GetApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponse = zod.object({
  "success": zod.boolean().default(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseSuccessDefault).describe('Indica se a requisição foi bem-sucedida'),
  "message": zod.string().optional().describe('Mensagem opcional de contexto'),
  "data": zod.object({
  "id": zod.uuid().describe('ID único do versículo'),
  "chapterId": zod.uuid().describe('ID do capítulo ao qual o versículo pertence'),
  "number": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponseDataOneNumberExclusiveMin).describe('Número do versículo'),
  "text": zod.string().describe('Texto do versículo')
}).describe('Versículo de um capítulo da Bíblia').and(zod.unknown().describe('Dados da resposta')).optional(),
  "pagination": zod.object({
  "currentPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationCurrentPageExclusiveMin).describe('Página atual'),
  "totalPages": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationTotalPagesExclusiveMin).describe('Número total de páginas'),
  "totalItems": zod.number().min(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationTotalItemsMin).describe('Número total de itens'),
  "itemsPerPage": zod.number().gt(getApiV1PublicBibleBooksDynamicIdChaptersNumberVersesVerseResponsePaginationItemsPerPageExclusiveMin).describe('Número de itens por página'),
  "hasNextPage": zod.boolean().describe('Indica se existe próxima página'),
  "hasPrevPage": zod.boolean().describe('Indica se existe página anterior')
}).optional().describe('Informações de paginação')
}).describe('Resposta de sucesso para GetVerseResponse')

