// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";
import { defineConfig } from "prisma/config";
import fs from "fs";
import path from "node:path";

const certPath = path.join(process.cwd(), process.env.DATABASE_CERT_PATH!);
const cert = fs.readFileSync(certPath, "utf-8");

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    ca: cert,
    cert: cert,
    key: cert,
    rejectUnauthorized: false,
  },
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
