name: CI - Api (Back-end)

on:
  pull_request:
    paths:
      - "apps/api/**"

  push:
    branches:
    paths:
      - "apps/api/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run Lint
        run: cd apps/api && bun run lint

  test:
    needs: lint
    env:
      NODE_ENV: test
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/test_db"
      DATABASE_CERT_PATH: ".certs/postgre-certificate.pem"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Create certificate directory
        run: mkdir -p apps/api/.certs

      - name: Create dummy certificate file
        run: echo "--- dummy cert ---" > apps/api/.certs/postgre-certificate.pem

      - name: Generate Drizzle
        run: cd apps/api && bun drizzle-kit generate

      - name: Run tests
        run: cd apps/api && bun run test
